from typing import Protocol

from app.domain import AuditLog, Project


class ProjectRepository(Protocol):
    def claim_capacity_and_create(self, project: Project) -> Project: ...

    def get_project(self, project_id: str) -> Project | None: ...

    def list_projects(self) -> list[Project]: ...

    def save_project(self, project: Project) -> Project: ...

    def release_capacity(self, project_id: str) -> Project: ...

    def append_audit_log(self, log: AuditLog) -> AuditLog: ...

    def list_audit_logs(self, project_id: str) -> list[AuditLog]: ...

    def health_check(self) -> dict[str, str]: ...
