apiVersion: v1
kind: Service
metadata:
  name: portal-frontend
  namespace: portal-system
spec:
  type: ClusterIP
  selector:
    app: portal-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
