apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-demo
  namespace: portal-system
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: portal-backend
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: portal-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portal-frontend
                port:
                  number: 80
